# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 22:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exambank', '0004_auto_20160824_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=20)),
                ('class_name', models.CharField(max_length=10)),
                ('class_num', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='pdf_file',
            field=models.FilePathField(default=datetime.datetime(2016, 8, 24, 22, 22, 57, 462550, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
