# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exambank', '0005_auto_20160824_2222'),
    ]

