# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exambank', '0007_auto_20160824_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='docfile_path',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pdf_file',
        ),
    ]
