# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exambank', '0008_auto_20160824_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.FilePathField(),
        ),
    ]
