# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exambank', '0009_auto_20160824_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.FilePathField(path=b'/Users/anahit/PycharmProjects/testbank/ExamSource/media'),
        ),
    ]
