# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exambank', '0010_auto_20160824_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='docfile',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_path',
        ),
        migrations.AddField(
            model_name='bank',
            name='file_name',
            field=models.CharField(default='.pdf', max_length=30),
        ),
    ]
