# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exambank', '0011_auto_20160824_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='docfile',
            field=models.FileField(default='.pdf', upload_to=b''),
        ),
    ]
