# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-25 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exambank', '0013_auto_20160825_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('class_shortName', models.CharField(max_length=100)),
                ('class_num', models.IntegerField()),
                ('file_name', models.CharField(default='.pdf', max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
