# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-26 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exambank', '0014_auto_20160825_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('class_shortName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=300)),
                ('professor_name', models.CharField(max_length=100)),
                ('file_year', models.IntegerField()),
                ('fileobj', models.FileField(upload_to=b'', verbose_name=models.CharField(max_length=300))),
                ('Classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exambank.Classes')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='library',
        ),
        migrations.AddField(
            model_name='classes',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exambank.Department'),
        ),
    ]
