# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-31 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exambank', '0016_auto_20160826_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=20)),
                ('class_name', models.CharField(max_length=10)),
                ('class_num', models.IntegerField()),
                ('file_name', models.CharField(default='.pdf', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.RemoveField(
            model_name='classes',
            name='department',
        ),
        migrations.RemoveField(
            model_name='files',
            name='classes',
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
